armor_hide:
  field_of_view: 1.7 # Проверка обзора игрока, вообще 1.5 норм работает, но при 1.7 это почти без склеек.
  # Чуть увеличим хит бокс игрока чтобы предиктом одевать ему броню при выходе из-за стены.
  expand_aabb:
    x: 0.2
    y: 0.2
    z: 0.2
  hide_meta: true # Скрывать ли чары и другие nbt теги на броне/предмете в руке.
  disable_worlds: # hide_meta игнорирует это
    - spawn