armor_hide:
  field_of_view: 1.7 # Проверка обзора игрока, вообще 1.5 норм работает, но при 1.7 это почти без склеек.
  # Чуть увеличим хит бокс игрока чтобы предиктом одевать ему броню при выходе из-за стены.
  expand_aabb:
    x: 0.2
    y: 0.2
    z: 0.2
  hide_meta: true # Скрывать ли чары и другие nbt теги на броне/предмете в руке.
  disable_worlds: # hide_meta игнорирует это
    - spawn


# Список прозрачных блоков
ignore_blocks:
  # с наковальней есть некоторые баги когда игрока видно, но броня всё равно скрыта
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  # air
  - AIR
  - VOID_AIR
  - CAVE_AIR
  - LEGACY_AIR
  # glass
  - GLASS
  - GLASS_PANE
  - WHITE_STAINED_GLASS
  - ORANGE_STAINED_GLASS
  - MAGENTA_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS
  - YELLOW_STAINED_GLASS
  - LIME_STAINED_GLASS
  - PINK_STAINED_GLASS
  - GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS
  - CYAN_STAINED_GLASS
  - PURPLE_STAINED_GLASS
  - BLUE_STAINED_GLASS
  - BROWN_STAINED_GLASS
  - GREEN_STAINED_GLASS
  - RED_STAINED_GLASS
  - BLACK_STAINED_GLASS
  - WHITE_STAINED_GLASS_PANE
  - ORANGE_STAINED_GLASS_PANE
  - MAGENTA_STAINED_GLASS_PANE
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - YELLOW_STAINED_GLASS_PANE
  - LIME_STAINED_GLASS_PANE
  - PINK_STAINED_GLASS_PANE
  - GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - CYAN_STAINED_GLASS_PANE
  - PURPLE_STAINED_GLASS_PANE
  - BLUE_STAINED_GLASS_PANE
  - BROWN_STAINED_GLASS_PANE
  - GREEN_STAINED_GLASS_PANE
  - RED_STAINED_GLASS_PANE
  - BLACK_STAINED_GLASS_PANE
  - GLASS_BOTTLE
  # water
  - WATER
  - BUBBLE_COLUMN
  # leaves
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - BIRCH_LEAVES
  - JUNGLE_LEAVES
  - ACACIA_LEAVES
  - DARK_OAK_LEAVES
  # fence
  - OAK_FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - ACACIA_FENCE
  - DARK_OAK_FENCE
  - CRIMSON_FENCE
  - WARPED_FENCE
  - OAK_FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - ACACIA_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - CRIMSON_FENCE_GATE
  - WARPED_FENCE_GATE
  - NETHER_BRICK_FENCE
  # trapdoor
  - OAK_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - BIRCH_TRAPDOOR
  - JUNGLE_TRAPDOOR
  - ACACIA_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - CRIMSON_TRAPDOOR
  - WARPED_TRAPDOOR
  - IRON_TRAPDOOR
  # door
  - OAK_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - BIRCH_TRAPDOOR
  - JUNGLE_TRAPDOOR
  - ACACIA_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - CRIMSON_TRAPDOOR
  - WARPED_TRAPDOOR
  - IRON_TRAPDOOR
  - IRON_DOOR
  - OAK_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - CRIMSON_DOOR
  - WARPED_DOOR
  # другие
  - LADDER
  - IRON_BARS
  - BELL
  - SLIME_BLOCK
  - HONEY_BLOCK